//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TingenNYQVIST.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://spectrumcsp.netsmartcloud.com/csp/spectrumsbox/avpm/WEBSVC.Query.cls")]
        public string TingenNYQVIST_NtstWsvcSboxQuery_Query {
            get {
                return ((string)(this["TingenNYQVIST_NtstWsvcSboxQuery_Query"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://spectrumcsp.netsmartcloud.com:443/csp/spectrumuat/avpm/WEBSVC.Query.cls")]
        public string TingenNYQVIST_NtstWsvcUatQuery_Query {
            get {
                return ((string)(this["TingenNYQVIST_NtstWsvcUatQuery_Query"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://spectrumcsp.netsmartcloud.com/csp/spectrum/avpm/WEBSVC.Query.cls")]
        public string TingenNYQVIST_NtstWsvcLiveQuery_Query {
            get {
                return ((string)(this["TingenNYQVIST_NtstWsvcLiveQuery_Query"]));
            }
        }
    }
}
